import { mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { basename, dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import type { GitConfigEntry } from "../types.js";
import { spawnFile } from "./process.js";

export type ExistingConfigEntry = {
  key: string;
  value: string;
};

export type WriteConfigResult = {
  path: string;
  written: GitConfigEntry[];
  skipped: GitConfigEntry[];
};

export type ManagedGitConfig = {
  gitdir: string;
  includePath: string;
  configPath: string;
  label: string;
};

type ManagedIncludeEntry = {
  gitdir: string;
  includePath: string;
};

const MANAGED_INCLUDE_START = "# [start] autogenerated by crgc";
const MANAGED_INCLUDE_END = "# [end] autogenerated by crgc";

export function getProjectGitConfigPath(cwd = process.cwd()): string {
  return join(cwd, ".gitconfig");
}

export function getHomeGitConfigPath(homeDir = homedir()): string {
  return join(homeDir, ".gitconfig");
}

export function getProjectPostfix(projectDir: string): string {
  const postfix = basename(resolve(projectDir));

  if (postfix.length === 0 || postfix === sep) {
    throw new Error("Unable to derive a gitconfig name from the project directory.");
  }

  return postfix;
}

export function resolveProjectDirectory(projectDir: string, homeDir = homedir()): string {
  if (projectDir === "~") {
    return homeDir;
  }

  if (projectDir.startsWith("~/")) {
    return resolve(homeDir, projectDir.slice(2));
  }

  return resolve(projectDir);
}

export function getGitdirCondition(projectDir: string, homeDir = homedir()): string {
  const absoluteProjectDir = resolveProjectDirectory(projectDir, homeDir);
  const relativeToHome = relative(homeDir, absoluteProjectDir);
  const useHomePrefix = relativeToHome.length > 0 && !relativeToHome.startsWith("..") && !isAbsolute(relativeToHome);
  const gitdir = useHomePrefix ? `~/${toGitPath(relativeToHome)}` : toGitPath(absoluteProjectDir);

  return ensureTrailingSlash(gitdir);
}

export async function getAvailableManagedGitConfigPath(postfix: string, homeDir = homedir()): Promise<string> {
  let suffix = "";
  let index = 0;

  while (true) {
    const configPath = join(homeDir, `.gitconfig.${postfix}${suffix}`);

    if (!(await fileExists(configPath))) {
      return configPath;
    }

    index += 1;
    suffix = `_${index}`;
  }
}

export async function ensureGitConfigFile(configPath: string): Promise<void> {
  await mkdir(dirname(configPath), { recursive: true });

  try {
    await stat(configPath);
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") {
      await spawnFile("git", ["config", "--file", configPath, "--add", "create-gitconfig.initialized", "true"]);
      await spawnFile("git", ["config", "--file", configPath, "--unset", "create-gitconfig.initialized"]);
      return;
    }

    throw error;
  }
}

export async function listManagedGitConfigs(homeConfigPath = getHomeGitConfigPath()): Promise<ManagedGitConfig[]> {
  const result = await spawnFile(
    "git",
    ["config", "--file", homeConfigPath, "--get-regexp", "^includeIf\\..*\\.path$"],
    {
      rejectOnError: false
    }
  );

  if (result.exitCode === 1) {
    return [];
  }

  if (result.exitCode !== 0) {
    throw new Error(result.stderr.trim() || `Unable to read includeIf entries from ${homeConfigPath}.`);
  }

  return result.stdout
    .split("\n")
    .filter((line) => line.trim().length > 0)
    .map((line) => parseManagedGitConfigLine(line, homeConfigPath))
    .filter((entry): entry is ManagedGitConfig => entry !== undefined);
}

export async function writeManagedInclude(homeConfigPath: string, gitdir: string, includePath: string): Promise<void> {
  await ensureGitConfigFile(homeConfigPath);
  const contents = await readFile(homeConfigPath, "utf8");

  await writeFile(homeConfigPath, upsertManagedInclude(contents, { gitdir, includePath }));
}

export async function removeManagedGitConfig(homeConfigPath: string, config: ManagedGitConfig): Promise<void> {
  await removeManagedInclude(homeConfigPath, config);
  await rm(config.configPath, { force: true });
}

export async function updateManagedGitConfigLocation(
  homeConfigPath: string,
  config: ManagedGitConfig,
  gitdir: string
): Promise<void> {
  if (config.gitdir === gitdir) {
    return;
  }

  await writeManagedInclude(homeConfigPath, gitdir, config.includePath);
  await removeManagedInclude(homeConfigPath, config);
}

async function removeManagedInclude(homeConfigPath: string, config: ManagedGitConfig): Promise<void> {
  const contents = await readFile(homeConfigPath, "utf8").catch((error: unknown) => {
    if (isNodeError(error) && error.code === "ENOENT") {
      return undefined;
    }

    throw error;
  });

  if (contents !== undefined) {
    const updatedContents = removeManagedIncludeFromBlock(contents, config.gitdir);

    if (updatedContents !== undefined) {
      await writeFile(homeConfigPath, updatedContents);
      return;
    }
  }

  const removeSection = await spawnFile(
    "git",
    ["config", "--file", homeConfigPath, "--remove-section", `includeIf.gitdir:${config.gitdir}`],
    {
      rejectOnError: false
    }
  );

  if (removeSection.exitCode !== 0 && removeSection.exitCode !== 1) {
    throw new Error(removeSection.stderr.trim() || `Unable to remove ${config.gitdir} from ${homeConfigPath}.`);
  }
}

export async function getConfigValue(configPath: string, key: string): Promise<string | undefined> {
  const result = await spawnFile("git", ["config", "--file", configPath, "--get", key], {
    rejectOnError: false
  });

  if (result.exitCode === 0) {
    return result.stdout.trimEnd();
  }

  if (result.exitCode === 1) {
    return undefined;
  }

  throw new Error(result.stderr.trim() || `Unable to read ${key} from ${configPath}.`);
}

export async function hasConfigValue(configPath: string, key: string): Promise<boolean> {
  return (await getConfigValue(configPath, key)) !== undefined;
}

export async function writeConfigEntries(
  configPath: string,
  entries: GitConfigEntry[],
  shouldReplace: (entry: GitConfigEntry, currentValue: string) => Promise<boolean>
): Promise<WriteConfigResult> {
  await ensureGitConfigFile(configPath);

  const written: GitConfigEntry[] = [];
  const skipped: GitConfigEntry[] = [];

  for (const entry of entries) {
    const currentValue = await getConfigValue(configPath, entry.key);

    if (currentValue !== undefined) {
      const replace = await shouldReplace(entry, currentValue);

      if (!replace) {
        skipped.push(entry);
        continue;
      }

      await spawnFile("git", ["config", "--file", configPath, "--replace-all", entry.key, entry.value]);
    } else {
      await spawnFile("git", ["config", "--file", configPath, "--add", entry.key, entry.value]);
    }

    written.push(entry);
  }

  return {
    path: configPath,
    written,
    skipped
  };
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") {
      return false;
    }

    throw error;
  }
}

function parseManagedGitConfigLine(line: string, homeConfigPath: string): ManagedGitConfig | undefined {
  const separatorIndex = line.search(/\s/);

  if (separatorIndex === -1) {
    return undefined;
  }

  const key = line.slice(0, separatorIndex);
  const includePath = line.slice(separatorIndex).trim();
  const match = /^includeif\.gitdir:(.+)\.path$/i.exec(key);

  if (match === null || !basename(includePath).startsWith(".gitconfig.")) {
    return undefined;
  }

  return {
    gitdir: match[1],
    includePath,
    configPath: resolveIncludePath(homeConfigPath, includePath),
    label: basename(includePath).replace(/^\.gitconfig\./, "")
  };
}

function upsertManagedInclude(contents: string, entry: ManagedIncludeEntry): string {
  const block = getManagedIncludeBlock(contents);

  if (block === undefined) {
    const separator = contents.trimEnd().length > 0 ? "\n\n" : "";

    return `${contents.trimEnd()}${separator}${formatManagedIncludeBlock([entry])}\n`;
  }

  const entries = parseManagedIncludeEntries(block.lines).filter((existing) => existing.gitdir !== entry.gitdir);
  entries.push(entry);

  return replaceManagedIncludeBlock(contents, block.start, block.end, formatManagedIncludeBlock(entries));
}

function removeManagedIncludeFromBlock(contents: string, gitdir: string): string | undefined {
  const block = getManagedIncludeBlock(contents);

  if (block === undefined) {
    return undefined;
  }

  const entries = parseManagedIncludeEntries(block.lines);

  if (!entries.some((entry) => entry.gitdir === gitdir)) {
    return undefined;
  }

  const remainingEntries = entries.filter((entry) => entry.gitdir !== gitdir);
  const replacement = remainingEntries.length > 0 ? formatManagedIncludeBlock(remainingEntries) : "";

  return replaceManagedIncludeBlock(contents, block.start, block.end, replacement);
}

function getManagedIncludeBlock(contents: string): { start: number; end: number; lines: string[] } | undefined {
  const lines = getConfigLines(contents);
  const start = lines.findIndex((line) => line.trim() === MANAGED_INCLUDE_START);

  if (start === -1) {
    return undefined;
  }

  const endOffset = lines.slice(start + 1).findIndex((line) => line.trim() === MANAGED_INCLUDE_END);

  if (endOffset === -1) {
    return undefined;
  }

  const end = start + 1 + endOffset;

  return {
    start,
    end,
    lines: lines.slice(start + 1, end)
  };
}

function parseManagedIncludeEntries(lines: string[]): ManagedIncludeEntry[] {
  const entries: ManagedIncludeEntry[] = [];

  for (let index = 0; index < lines.length; index += 1) {
    const headerMatch = /^\s*\[includeIf\s+"gitdir:(.+)"\]\s*$/i.exec(lines[index]);

    if (headerMatch === null) {
      continue;
    }

    for (let sectionIndex = index + 1; sectionIndex < lines.length; sectionIndex += 1) {
      if (/^\s*\[/.test(lines[sectionIndex])) {
        index = sectionIndex - 1;
        break;
      }

      const pathMatch = /^\s*path\s*=\s*(.+?)\s*$/.exec(lines[sectionIndex]);

      if (pathMatch !== null) {
        entries.push({
          gitdir: headerMatch[1],
          includePath: pathMatch[1]
        });
        break;
      }
    }
  }

  return entries;
}

function formatManagedIncludeBlock(entries: ManagedIncludeEntry[]): string {
  return [
    MANAGED_INCLUDE_START,
    "#",
    ...entries.flatMap((entry) => [`[includeIf "gitdir:${entry.gitdir}"]`, `\tpath = ${entry.includePath}`]),
    "#",
    MANAGED_INCLUDE_END
  ].join("\n");
}

function replaceManagedIncludeBlock(contents: string, start: number, end: number, replacement: string): string {
  const lines = getConfigLines(contents);
  const nextLines = [...lines.slice(0, start), ...getConfigLines(replacement), ...lines.slice(end + 1)];

  return tidyConfigLines(nextLines);
}

function getConfigLines(contents: string): string[] {
  return contents.replace(/\r\n/g, "\n").split("\n");
}

function tidyConfigLines(lines: string[]): string {
  const contents = lines
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd();

  return contents.length > 0 ? `${contents}\n` : "";
}

function resolveIncludePath(homeConfigPath: string, includePath: string): string {
  if (includePath === "~") {
    return homedir();
  }

  if (includePath.startsWith("~/")) {
    return join(homedir(), includePath.slice(2));
  }

  if (isAbsolute(includePath)) {
    return includePath;
  }

  return join(dirname(homeConfigPath), includePath);
}

function ensureTrailingSlash(path: string): string {
  return path.endsWith("/") ? path : `${path}/`;
}

function toGitPath(path: string): string {
  return path.split(sep).join("/");
}
